server:
  port: 8081

spring:
  application:
    name: FakerApplication
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vc_library
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB

file:
  upload-dir: